name = "power"
name_pretty = "Power"
icon = "system-shutdown"

[[entries]]
text = "Logout"
keywords = ["logout", "exit"]
icon = "⚿"
actions = { "logout" = "swaymsg exit" }

[[entries]]
text = "Suspend"
keywords = ["sleep", "suspend"]
icon = "⏾"
actions = { "suspend" = "systemctl suspend" }

[[entries]]
text = "Shutdown"
keywords = ["poweroff", "shutdown"]
icon = "⏻"
actions = { "shutdown" = "systemctl poweroff" }

[[entries]]
text = "Restart"
keywords = ["reboot", "restart"]
icon = "⏼"
actions = { "restart" = "systemctl reboot" }
