theme = "wofi"
close_when_open = true
click_to_close = true
force_keyboard_focus = true
hide_quick_activation = true
global_argument_delimiter = "#"
exact_search_prefix = "'"

[placeholders]
"default" = { input = "Search for an Application", list = "No Results" }

[providers]
default = ["desktopapplications", "calc", "menus"]
empty = ["desktopapplications"]
max_results = 50

[providers.sets.powermenu]
default = ["menus:power"]
empty = ["menus:power"]

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[providers.providerlist]
filter = ["desktopapplications", "calc", "menus"]

[providers.sets.screenshot]
default = ["menus:screenshot"]
empty = ["menus:screenshot"]
